# get character names
query_name {
    characters {
        results {
            name
        }
    }
}

# get character status
query_status {
    characters {
        results {
            status
        }
    }
}

# get character info
query_info {
    characters {
        # many character attributes
        results {
            name
            status
            species
            type
            gender
        }
    }
}